In [53]:
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("TKAgg")
from matplotlib import pyplot as plt
%matplotlib
from matplotlib import animation

import os
os.chdir('/Users/PG/Paolo/python_repos/language_proj/lang_model_simple')

Using matplotlib backend: MacOSX


//anaconda/lib/python3.5/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


In [30]:
import deepdish as dd
ex_ICs = dd.io.load('IC_lang_ONLY_SPOKEN_1000_steps.h5')

In [54]:
from imp import reload
import agent_simple
import model_simple
reload(agent_simple)
reload(model_simple)
from model_simple import Simple_Language_Model
m1 = Simple_Language_Model(100, width=5, height=5, num_cities=1,
                           init_lang_distrib=[0.75, 0.25, 0.],
                           lang_ags_sorted_by_dist=False, lang_ags_sorted_in_clust=False)
m1.run_model(2000, recording_steps_period=400)
m1.save_model_data()

//anaconda/lib/python3.5/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full(1000, 1000) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
0%                          100%
[##                            ] | ETA: 00:26:55

KeyboardInterrupt: 

In [59]:
m1.clusters_info[0]['jobs'][2].num_places

48

In [51]:
l_1 = [ag for ag in m1.schedule.agents if ag.language == 0]
l_bil = [ag for ag in m1.schedule.agents if ag.language == 1]
l_2 = [ag for ag in m1.schedule.agents if ag.language == 2]

In [7]:
ag_try=l_1[0]

In [12]:
i=21
plt.plot(l_bil[i].lang_stats['L1']['pct'][:1100], label='L1')
plt.plot(l_bil[i].lang_stats['L2']['pct'][:1100], label='L2')
plt.legend()

In [9]:
l_bil[i].lang_stats['L2']['R']

array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        0.99415622,  1.        ,  0.99270987,  0.99263619,  1.        ,
        0.99109565,  0.99105367,  0.98939873,  0.99002043,  0.98901747,
        0.98775928,  1.        ,  0.98699287,  0.98673611,  0.98566351,
        1.        ,  0.98361785,  0.98443782,  0.97872104,  0.98367216,
        0.98126928,  1.        ,  0.97651402,  0.97527444,  0.9789739 ,
        0.9767082 ,  0.97273853,  0.97736684,  0.97505005,  0.96884088,
        1.        ,  1.        ,  1.        ,  0.96630047,  0.97167394,
        0.96636197,  0.97025447,  0.97199758,  0.97294243,  0.96215189,
        1.        ,  0.95893365,  0.96508955,  0.96425089,  0.96086441,
        0.96641986,  0.95512247,  0.96259109,  0.96437809,  0.96006544,
        0.95723693,  1.        ,  0.95030337,  0.95653548,  1.  

In [70]:
l_bil[i].lang_stats['L1']['pct']

array([ 0.004,  0.008,  0.009, ...,  0.   ,  0.   ,  0.   ])

In [23]:
ag_try.city_idx

0

In [17]:
ag_try.home_coords, ag_try.job_coords, ag_try.school_coords

((1, 1), (2, 1), (1, 1))

In [288]:
len(l_1),len(l_bil),len(l_2)

(63, 137, 0)

In [202]:
#l_bil[24].lang_stats['L2']['t']
i=5
l = 'L2'

In [155]:
R=np.exp(-l_bil[i].k*l_bil[i].lang_stats[l]['t']/l_bil[i].lang_stats[l]['S'])
np.where(R>0.9)[0].shape[0] / 1000

0.406

In [171]:
np.where((l_1[0].lang_stats['L1']['t'] - m1.lang_ICs['100_pct']['t']) >= 50)[0].shape

(560,)

In [238]:
(l_1[0].lang_stats['L1']['wc'] - m1.lang_ICs['100_pct']['wc']).sum()

891

In [250]:
(np.where(l_1[0].lang_stats['L1']['R'] > 0.9)[0].shape[0] / m1.vocab_red)

0.784

In [40]:
for ag in l_1:
    print(ag.lang_stats['L1']['R'][:500].mean())

0.958925942519
0.955580365605
0.957882162428
0.954781045135
0.953190880075
0.958769056969
0.956508006907
0.953932262238
0.951110262792
0.955539039578
0.044
0.955674574447
0.951374914112
0.954251401038
0.058
0.950451191645
0.957251629416
0.953058064959
0.953154127286
0.951829862757
0.957642074626
0.950966349183
0.956744456189
0.955362478
0.953005007776
0.955834715815
0.955371122708
0.953435062
0.958776417484
0.955605613547
0.953691101827
0.955618775064
0.952119634312
0.952953435628
0.955082665806
0.953892082762
0.95173813329
0.955033517679
0.953349798818
0.952003317588
0.956337130338
0.954811316193
0.959680429562
0.956506371241
0.953396529861
0.956925932584
0.956482162316
0.950635810368
0.953941619184
0.955262360096
0.950817518833
0.951279322222
0.04
0.95422848929
0.956613933457
0.026
0.952979383431
0.954285212518
0.954956460084
0.956206829125
0.956656350559
0.034
0.957773984672
0.046
0.952808598238
0.955529713181
0.954484726189
0.952973108546
0.955995007659
0.954800546938
0.95791435820

In [52]:

#estimate of spoken words per day
w_step_list=[]
for ag in l_1:
    w_step = 40 * (ag.lang_stats['L1']['wc'] - m1.lang_ICs['100_pct']['wc']).sum()/(m1.schedule.steps*10)
    print(w_step)
    w_step_list.append(w_step)
w_step_list = np.array(w_step_list)

5704.0
9932.0
7856.0
2852.0
8496.0
9860.0
7104.0
4660.0
9192.0
7100.0
6336.0
7084.0
5708.0
5688.0
9980.0
9660.0
5664.0
10660.0
4968.0
5696.0
5716.0
6400.0
4940.0
5688.0
7068.0
4260.0
5684.0
7808.0
5672.0
6368.0
6384.0
7088.0
5688.0
5368.0
6796.0
4928.0
7100.0
5004.0
4292.0
4952.0
4284.0
6332.0
4980.0
5552.0
4964.0
4932.0
5704.0
4964.0
6856.0
4292.0
9268.0
5020.0
4256.0
6364.0
8540.0
-23570372.0
5668.0
6104.0
5696.0
7792.0
7536.0
4956.0
9916.0
6376.0
4900.0
7112.0
5664.0
8476.0
7808.0
6832.0
6316.0
5028.0
6436.0
6816.0
7792.0
9144.0
4280.0
9872.0
8532.0
7140.0
9200.0


In [42]:
m1.schedule.steps

20

In [257]:
np.where(np.exp(-l_bil[0].k * m1.lang_ICs['25_pct']['t']/m1.lang_ICs['25_pct']['S']) > 0.9)[0].shape[0]/1000

0.53

In [52]:
age=1699
bil_pcts = [(ag.lang_stats['L1']['pct'][age], ag.lang_stats['L2']['pct'][age], age) 
             for ag in m1.schedule.agents
             if ag.language == 1]
mono_pcts = [(ag.lang_stats['L1']['pct'][age], ag.lang_stats['L2']['pct'][age], age) 
 for ag in m1.schedule.agents
                       if ag.language == 0]

In [53]:
mono_pcts

[(0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 

In [73]:
max(list(zip(*bil_pcts))[1]), max(list(zip(*mono_pcts))[0])

(0.41899999999999998, 0.47599999999999998)

In [74]:
min(list(zip(*bil_pcts))[1]), min(list(zip(*mono_pcts))[0])

(0.129, 0.434)

In [75]:
from collections import Counter
ccs=Counter(list(zip(*bil_pcts))[1])

In [76]:
ccs.most_common()

[(0.39200000000000002, 2),
 (0.23799999999999999, 2),
 (0.29499999999999998, 2),
 (0.16200000000000001, 1),
 (0.20100000000000001, 1),
 (0.23000000000000001, 1),
 (0.39500000000000002, 1),
 (0.312, 1),
 (0.29099999999999998, 1),
 (0.158, 1),
 (0.39600000000000002, 1),
 (0.41899999999999998, 1),
 (0.32400000000000001, 1),
 (0.129, 1),
 (0.248, 1),
 (0.33300000000000002, 1),
 (0.29299999999999998, 1),
 (0.34999999999999998, 1),
 (0.28899999999999998, 1)]

In [269]:
age = 1520
list_biling = [ag.lang_stats['L2']['pct'][age] for ag in m1.schedule.agents
               if ag.language == 1]
np.array(list_biling).mean()

0.46753191489361701

In [180]:
R=np.exp(-l_1[0].k * l_1[0].lang_stats['L1']['t'] / l_1[0].lang_stats['L1']['S'])
np.where(R>0.75)[0].shape[0] / 1000

0.661

In [159]:
for j, ag in enumerate(l_1):
    plt.plot(l_1[j].lang_stats['L1']['pct'])

In [304]:
for j, ag in enumerate(l_bil):
    plt.plot(l_bil[j].lang_stats['L1']['pct'])

In [157]:
for j, ag in enumerate(l_2):
    plt.plot(l_2[j].lang_stats['L2']['pct'])

In [15]:
#l_bil[i].lang_stats[l]['pct'],l_bil[i].lang_stats[l]['t'], l_bil[i].lang_stats[l]['S']

In [60]:
R=np.exp(-l_bil[i].k*l_bil[i].lang_stats[l]['t']/l_bil[i].lang_stats[l]['S'])
np.where(R>0.9)[0].shape[0] / 1000

0.09

In [20]:
import deepdish as dd

In [204]:
IC_imps = dd.io.load('IC_lang_1500_steps.h5')

In [118]:
IC_imps['25_pct']['t'].dtype, IC_imps['25_pct']['S'].dtype, IC_imps['25_pct']['wc'].dtype

(dtype('int64'), dtype('float64'), dtype('int32'))

In [75]:
m1.lang_ICs['100_pct']['wc'].dtype

dtype('uint32')

In [77]:
a, a_c = np.unique([21,3,21,3,4,5,4], return_counts=True)

In [94]:
a_c

array([2, 2, 1, 2])

In [146]:
l_bil[0].k

0.10536051565782635

In [200]:
R=np.exp(-l_bil[0].k*IC_imps['25_pct']['t']/IC_imps['25_pct']['S'])
np.where(R >= 0.9)[0].shape[0]/1000

0.53

In [197]:
IC_imps['25_pct']['t'] = IC_imps['25_pct']['t'] + 1

In [198]:
R=np.exp(-l_bil[0].k*IC_imps['25_pct']['t']/IC_imps['25_pct']['S'])
np.where(R > 0.9)[0].shape[0]/1000

0.524

In [152]:
R=np.exp(-l_bil[0].k*IC_imps['50_pct']['t']/IC_imps['50_pct']['S'])
np.where(R > 0.9)[0].shape[0]/1000

0.66

In [205]:
R=np.exp(-l_bil[0].k*IC_imps['100_pct']['t']/IC_imps['100_pct']['S'])
np.where(R >=0.9)[0].shape[0]/1000

0.792

In [220]:
IC_imps['100_pct']['t'] = IC_imps['100_pct']['t'] + 1

In [221]:
R=np.exp(-l_bil[0].k*IC_imps['100_pct']['t']/IC_imps['100_pct']['S'])
np.where(R > 0.9)[0].shape[0]/1000

0.724

In [40]:
ag1=[ag for ag in m1.schedule.agents if ag.unique_id == 1][0]

CODE PROFILING

In [1]:
%load_ext line_profiler

In [8]:
%lprun -f m1.schedule.step m1.run_model(1)

0%  100%
[#] | ETA: 00:00:00
Total time elapsed: 00:00:00


In [16]:
%lprun -f l_bil[0].speak_choice_model m1.run_model(1)

0%  100%
[#] | ETA: 00:00:00
Total time elapsed: 00:00:00


In [17]:
%lprun -f l_bil[0].update_lang_arrays m1.run_model(1)

0%  100%
[#] | ETA: 00:00:00
Total time elapsed: 00:00:00


In [79]:
l_bil[0].lang_stats['L2']['t']

array([ 162,  162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
        162,  164,  162,  162,  162,  164,  164,  164,  162,  166,  165,
        171,  165,  164,  164,  164,  165,  172,  162,  164,  172,  162,
        162,  171,  165,  162,  162,  164,  166,  165,  164,  162,  175,
        162,  200,  171,  165,  172,  166,  172,  166,  200,  164,  195,
        162,  200,  171,  164,  172,  165,  162,  165,  200,  195,  200,
        197,  162,  164,  188,  164,  166,  162,  200,  188,  195,  171,
        200,  162,  200,  164,  200,  165,  200,  200,  200,  171,  175,
        200,  188,  188,  172,  200,  200,  162,  165,  202,  200,  175,
        188,  200,  162,  200,  197,  200,  164,  200,  191,  188,  200,
        200,  200,  200,  200,  188,  172,  197,  200,  200,  200,  197,
        200,  200,  200,  191,  200,  166,  200,  188,  164,  200,  200,
        200,  200,  202,  175,  200,  200,  201,  200,  164,  200,  201,
        165,  200,  200,  200,  200,  200,  200,  2

In [90]:
kernel = np.array([[0, 1, 0], [1,-4, 1], [0, 1, 0]])

arr=np.ones((10,10))
arr[2,4] = 5
arr[2,5] = 8
arr

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  5.,  8.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [91]:
from scipy.signal import correlate2d

In [93]:
correlate2d(arr, kernel, mode='same')

array([[ -2.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -2.],
       [ -1.,   0.,   0.,   0.,   4.,   7.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   4.,  -9., -24.,   7.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   4.,   7.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -2.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -2.]])

In [96]:
%%writefile f1.py 
import numpy as np
np.array([1,2,3])

Writing f1.py


In [97]:
%%writefile f1.py -a
import pandas as pd
pd.DataFrame({'a':[1,33,44]})

Appending to f1.py


In [98]:
ls

IC_lang_1500_steps.h5            model_data.h5
__pycache__/                     model_lang_incentives/
activate_networks/               model_simple.py
agent_simple.py                  step1000.png
alpha_vs_step_dict.h5            step200.png
cdf_Mand_vs_step_dict.h5         step400.png
cdfs_3R_vs_step.h5               step600.png
debug.py                         step800.png
justry/                          transf_to_sorted_vocab_union.h5
limited_lifespan_agents/         zipf_generator/
