In [40]:
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("TKAgg")
from matplotlib import pyplot as plt
%matplotlib
from matplotlib import animation

import os
os.chdir('/Users/PG/Paolo/python_repos/language_proj/lang_model_simple')

Using matplotlib backend: MacOSX


//anaconda/lib/python3.5/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


In [73]:
from imp import reload
import agent_simple
import model_simple
reload(agent_simple)
reload(model_simple)
from model_simple import Simple_Language_Model
m1 = Simple_Language_Model(100, width=5, height=5, num_cities=1,
                           init_lang_distrib=[0.8, 0.2, 0.],
                           lang_ags_sorted_by_dist=False, lang_ags_sorted_in_clust=False)
m1.run_model(500, recording_steps_period=100)

//anaconda/lib/python3.5/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full(1000, 1000) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
0%                          100%
[#####                         ] | ETA: 00:04:37//anaconda/lib/python3.5/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
[##############################] | ETA: 00:00:00
Total time elapsed: 00:09:24


In [39]:
#m1.clusters_info[0]['schools'][0].pos
m1.clusters_info.keys()

dict_keys([0])

In [66]:
l_1 = [ag for ag in m1.schedule.agents if ag.language == 0]
l_bil = [ag for ag in m1.schedule.agents if ag.language == 1]
l_2 = [ag for ag in m1.schedule.agents if ag.language == 2]

In [54]:
ag_try=l_1[0]

In [72]:
i=21
plt.plot(l_bil[i].lang_stats['L1']['pct'], label='L1')
plt.plot(l_bil[i].lang_stats['L2']['pct'], label='L2')
plt.legend()

In [70]:
l_bil[i].lang_stats['L1']['pct']

array([ 0.004,  0.008,  0.009, ...,  0.   ,  0.   ,  0.   ])

In [23]:
ag_try.city_idx

0

In [17]:
ag_try.home_coords, ag_try.job_coords, ag_try.school_coords

((1, 1), (2, 1), (1, 1))

In [288]:
len(l_1),len(l_bil),len(l_2)

(63, 137, 0)

In [202]:
#l_bil[24].lang_stats['L2']['t']
i=5
l = 'L2'

In [155]:
R=np.exp(-l_bil[i].k*l_bil[i].lang_stats[l]['t']/l_bil[i].lang_stats[l]['S'])
np.where(R>0.9)[0].shape[0] / 1000

0.406

In [171]:
np.where((l_1[0].lang_stats['L1']['t'] - m1.lang_ICs['100_pct']['t']) >= 50)[0].shape

(560,)

In [238]:
(l_1[0].lang_stats['L1']['wc'] - m1.lang_ICs['100_pct']['wc']).sum()

891

In [250]:
(np.where(l_1[0].lang_stats['L1']['R'] > 0.9)[0].shape[0] / m1.vocab_red)

0.784

In [255]:
w_step_list=[]
for ag in l_1:
    w_step_list.append(40*(ag.lang_stats['L1']['wc'] - m1.lang_ICs['100_pct']['wc']).sum()/50)
w_step_list = np.array(w_step_list)

In [256]:
w_step_list.mean()

9659.1542857142867

In [257]:
np.where(np.exp(-l_bil[0].k * m1.lang_ICs['25_pct']['t']/m1.lang_ICs['25_pct']['S']) > 0.9)[0].shape[0]/1000

0.53

In [52]:
age=1699
bil_pcts = [(ag.lang_stats['L1']['pct'][age], ag.lang_stats['L2']['pct'][age], age) 
             for ag in m1.schedule.agents
             if ag.language == 1]
mono_pcts = [(ag.lang_stats['L1']['pct'][age], ag.lang_stats['L2']['pct'][age], age) 
 for ag in m1.schedule.agents
                       if ag.language == 0]

In [53]:
mono_pcts

[(0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 1699),
 (0.0, 0.0, 

In [73]:
max(list(zip(*bil_pcts))[1]), max(list(zip(*mono_pcts))[0])

(0.41899999999999998, 0.47599999999999998)

In [74]:
min(list(zip(*bil_pcts))[1]), min(list(zip(*mono_pcts))[0])

(0.129, 0.434)

In [75]:
from collections import Counter
ccs=Counter(list(zip(*bil_pcts))[1])

In [76]:
ccs.most_common()

[(0.39200000000000002, 2),
 (0.23799999999999999, 2),
 (0.29499999999999998, 2),
 (0.16200000000000001, 1),
 (0.20100000000000001, 1),
 (0.23000000000000001, 1),
 (0.39500000000000002, 1),
 (0.312, 1),
 (0.29099999999999998, 1),
 (0.158, 1),
 (0.39600000000000002, 1),
 (0.41899999999999998, 1),
 (0.32400000000000001, 1),
 (0.129, 1),
 (0.248, 1),
 (0.33300000000000002, 1),
 (0.29299999999999998, 1),
 (0.34999999999999998, 1),
 (0.28899999999999998, 1)]

In [269]:
age = 1520
list_biling = [ag.lang_stats['L2']['pct'][age] for ag in m1.schedule.agents
               if ag.language == 1]
np.array(list_biling).mean()

0.46753191489361701

In [180]:
R=np.exp(-l_1[0].k * l_1[0].lang_stats['L1']['t'] / l_1[0].lang_stats['L1']['S'])
np.where(R>0.75)[0].shape[0] / 1000

0.661

In [159]:
for j, ag in enumerate(l_1):
    plt.plot(l_1[j].lang_stats['L1']['pct'])

In [304]:
for j, ag in enumerate(l_bil):
    plt.plot(l_bil[j].lang_stats['L1']['pct'])

In [157]:
for j, ag in enumerate(l_2):
    plt.plot(l_2[j].lang_stats['L2']['pct'])

In [15]:
#l_bil[i].lang_stats[l]['pct'],l_bil[i].lang_stats[l]['t'], l_bil[i].lang_stats[l]['S']

In [60]:
R=np.exp(-l_bil[i].k*l_bil[i].lang_stats[l]['t']/l_bil[i].lang_stats[l]['S'])
np.where(R>0.9)[0].shape[0] / 1000

0.09

In [20]:
import deepdish as dd

In [204]:
IC_imps = dd.io.load('IC_lang_1500_steps.h5')

In [118]:
IC_imps['25_pct']['t'].dtype, IC_imps['25_pct']['S'].dtype, IC_imps['25_pct']['wc'].dtype

(dtype('int64'), dtype('float64'), dtype('int32'))

In [75]:
m1.lang_ICs['100_pct']['wc'].dtype

dtype('uint32')

In [77]:
a, a_c = np.unique([21,3,21,3,4,5,4], return_counts=True)

In [94]:
a_c

array([2, 2, 1, 2])

In [146]:
l_bil[0].k

0.10536051565782635

In [200]:
R=np.exp(-l_bil[0].k*IC_imps['25_pct']['t']/IC_imps['25_pct']['S'])
np.where(R >= 0.9)[0].shape[0]/1000

0.53

In [197]:
IC_imps['25_pct']['t'] = IC_imps['25_pct']['t'] + 1

In [198]:
R=np.exp(-l_bil[0].k*IC_imps['25_pct']['t']/IC_imps['25_pct']['S'])
np.where(R > 0.9)[0].shape[0]/1000

0.524

In [152]:
R=np.exp(-l_bil[0].k*IC_imps['50_pct']['t']/IC_imps['50_pct']['S'])
np.where(R > 0.9)[0].shape[0]/1000

0.66

In [205]:
R=np.exp(-l_bil[0].k*IC_imps['100_pct']['t']/IC_imps['100_pct']['S'])
np.where(R >=0.9)[0].shape[0]/1000

0.792

In [220]:
IC_imps['100_pct']['t'] = IC_imps['100_pct']['t'] + 1

In [221]:
R=np.exp(-l_bil[0].k*IC_imps['100_pct']['t']/IC_imps['100_pct']['S'])
np.where(R > 0.9)[0].shape[0]/1000

0.724

In [40]:
ag1=[ag for ag in m1.schedule.agents if ag.unique_id == 1][0]

CODE PROFILING

In [1]:
%load_ext line_profiler

In [8]:
%lprun -f m1.schedule.step m1.run_model(1)

0%  100%
[#] | ETA: 00:00:00
Total time elapsed: 00:00:00


In [16]:
%lprun -f l_bil[0].speak_choice_model m1.run_model(1)

0%  100%
[#] | ETA: 00:00:00
Total time elapsed: 00:00:00


In [17]:
%lprun -f l_bil[0].update_lang_arrays m1.run_model(1)

0%  100%
[#] | ETA: 00:00:00
Total time elapsed: 00:00:00


In [79]:
l_bil[0].lang_stats['L2']['t']

array([ 162,  162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
        162,  164,  162,  162,  162,  164,  164,  164,  162,  166,  165,
        171,  165,  164,  164,  164,  165,  172,  162,  164,  172,  162,
        162,  171,  165,  162,  162,  164,  166,  165,  164,  162,  175,
        162,  200,  171,  165,  172,  166,  172,  166,  200,  164,  195,
        162,  200,  171,  164,  172,  165,  162,  165,  200,  195,  200,
        197,  162,  164,  188,  164,  166,  162,  200,  188,  195,  171,
        200,  162,  200,  164,  200,  165,  200,  200,  200,  171,  175,
        200,  188,  188,  172,  200,  200,  162,  165,  202,  200,  175,
        188,  200,  162,  200,  197,  200,  164,  200,  191,  188,  200,
        200,  200,  200,  200,  188,  172,  197,  200,  200,  200,  197,
        200,  200,  200,  191,  200,  166,  200,  188,  164,  200,  200,
        200,  200,  202,  175,  200,  200,  201,  200,  164,  200,  201,
        165,  200,  200,  200,  200,  200,  200,  2

In [90]:
kernel = np.array([[0, 1, 0], [1,-4, 1], [0, 1, 0]])

arr=np.ones((10,10))
arr[2,4] = 5
arr[2,5] = 8
arr

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  5.,  8.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [91]:
from scipy.signal import correlate2d

In [93]:
correlate2d(arr, kernel, mode='same')

array([[ -2.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -2.],
       [ -1.,   0.,   0.,   0.,   4.,   7.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   4.,  -9., -24.,   7.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   4.,   7.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -1.],
       [ -2.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -2.]])

In [96]:
%%writefile f1.py 
import numpy as np
np.array([1,2,3])

Writing f1.py


In [97]:
%%writefile f1.py -a
import pandas as pd
pd.DataFrame({'a':[1,33,44]})

Appending to f1.py


In [98]:
ls

IC_lang_1500_steps.h5            model_data.h5
__pycache__/                     model_lang_incentives/
activate_networks/               model_simple.py
agent_simple.py                  step1000.png
alpha_vs_step_dict.h5            step200.png
cdf_Mand_vs_step_dict.h5         step400.png
cdfs_3R_vs_step.h5               step600.png
debug.py                         step800.png
justry/                          transf_to_sorted_vocab_union.h5
limited_lifespan_agents/         zipf_generator/
